name: smartpag_core
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none  

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  equatable: ^2.0.5
  pretty_dio_logger: ^1.3.1
  logger: ^2.0.2+1
  dio: ^5.3.3
  flutter_screenutil: ^5.9.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^8.0.0
  package_info_plus: ^4.1.0
  jwt_decoder: ^2.0.1
  flutter_svg: ^2.0.0
  dartz: ^0.10.1
  connectivity_plus: ^5.0.0
  url_launcher: ^6.2.1
  shared_preferences: ^2.0.13
  mask_text_input_formatter: ^2.5.0
  intl: ^0.18.1
  local_auth: ^2.1.7
  local_auth_ios: any 
  corsac_jwt: '1.0.0-nullsafety.1'
  device_info_plus: ^9.1.0
  nfc_manager: ^3.3.0
  open_filex: ^4.3.4
  path_provider: ^2.1.1
  share_plus: ^7.1.0
  circular_countdown_timer: ^0.2.3
  device_info_plus_platform_interface: ^7.0.0
  ffi: ^2.0.1
  carousel_slider: ^4.2.1
  #lottie: ^2.6.0
  flutter_phone_direct_caller: ^2.1.1
  #flutter_advanced_networkimage_2: ^2.0.1
  rxdart: ^0.27.7 
  sms_autofill: ^2.3.0
  #Firebase
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  firebase_analytics: ^10.0.4
  firebase_crashlytics: ^3.3.4
  firebase_dynamic_links: ^5.3.4
  firebase_remote_config: ^4.2.4
  permission_handler: ^11.3.0
  ## Dependencias Utilizadas para Test.
  mocktail: ^1.0.1
  mockingjay: ^0.4.0
  geolocator: ^11.0.0
  ## Lib da camada Domino sem referencias obedecendo a sobre-escrita 
  smartpag_domain:
       git:
         url: "https://github.com/gianlucagodoy/smartpag-domain"
         ref: v1.0.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  
