// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptionsPartnerDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCez5_IW8oIH_HAsw0A71Iz0NHWR1iMRDo',
    appId: '1:916769283604:android:28ad6752ddfb3d470c9101',
    messagingSenderId: '916769283604',
    projectId: 'zukpay-65fed',
    storageBucket: 'zukpay-65fed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAphrOz0HpV459WYwY1j1hp9YecCGZNn48',
    appId: '1:121070433098:ios:3422380b3ddd41066a07b3',
    messagingSenderId: '121070433098',
    projectId: 'appcliente-parceiros',
    storageBucket: 'appcliente-parceiros.appspot.com',
    iosClientId:
        '121070433098-5ifgo205qdohsq43d985t35arufihr7n.apps.googleusercontent.com',
    iosBundleId: 'pagocartoes.com.br.pago.partner0.dev',
  );
}
